# Generated by Django 4.2.3 on 2023-07-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("investorapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("verification_time", models.PositiveIntegerField()),
                (
                    "superior_limit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "inferior_limit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="email",
            old_name="endereco",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="email",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Ativo",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
        migrations.AddField(
            model_name="asset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="investorapp.user"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="investorapp.user",
            ),
            preserve_default=False,
        ),
    ]
