# Generated by Django 4.2.3 on 2023-07-08 22:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("investorapp", "0002_asset_user_rename_endereco_email_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="Name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="Name",
            new_name="name",
        ),
    ]
