# Generated by Django 4.2.3 on 2023-07-08 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("investorapp", "0003_rename_name_asset_name_rename_name_user_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="email",
            old_name="address",
            new_name="email",
        ),
    ]
