# Generated by Django 4.2.3 on 2023-07-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investorapp", "0004_rename_address_email_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="email",
            field=models.CharField(max_length=100),
        ),
    ]
