# Generated by Django 4.2.3 on 2023-07-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investorapp", "0005_alter_email_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="email",
        ),
        migrations.AddField(
            model_name="email",
            name="address",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
    ]
