# Generated by Django 4.2.3 on 2023-07-09 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("investorapp", "0006_remove_email_email_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
